title: Aaron Onyan
logo: Aaron.jpeg
description: I am a Data Analyst with extensive experience analyzing data using Advanced Excel for report automation, SQL for data interrogation and manipulation, PowerBI for data visualization and creating business intelligence reports.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
